// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WebMVC_DinhTienManh_22103100308.Models;

#nullable disable

namespace WebMVC_DinhTienManh_22103100308.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20250601162710_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.36")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("WebMVC_DinhTienManh_22103100308.Models.Result", b =>
                {
                    b.Property<int>("ResultID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ResultID"), 1L, 1);

                    b.Property<float>("Score")
                        .HasColumnType("real");

                    b.Property<int>("StudentID")
                        .HasColumnType("int");

                    b.Property<string>("Subject")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("ResultID");

                    b.HasIndex("StudentID");

                    b.ToTable("Results");

                    b.HasData(
                        new
                        {
                            ResultID = 1,
                            Score = 9f,
                            StudentID = 1,
                            Subject = "Toán"
                        },
                        new
                        {
                            ResultID = 2,
                            Score = 8f,
                            StudentID = 1,
                            Subject = "Van"
                        },
                        new
                        {
                            ResultID = 3,
                            Score = 8f,
                            StudentID = 2,
                            Subject = "Ly"
                        },
                        new
                        {
                            ResultID = 4,
                            Score = 7f,
                            StudentID = 2,
                            Subject = "Hoa"
                        },
                        new
                        {
                            ResultID = 5,
                            Score = 8f,
                            StudentID = 3,
                            Subject = "Anh"
                        },
                        new
                        {
                            ResultID = 6,
                            Score = 7f,
                            StudentID = 3,
                            Subject = "Su"
                        });
                });

            modelBuilder.Entity("WebMVC_DinhTienManh_22103100308.Models.Student", b =>
                {
                    b.Property<int>("StudentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("StudentId"), 1L, 1);

                    b.Property<DateTime>("BrithDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("StudentId");

                    b.ToTable("Students");

                    b.HasData(
                        new
                        {
                            StudentId = 1,
                            BrithDate = new DateTime(2002, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FullName = "A"
                        },
                        new
                        {
                            StudentId = 2,
                            BrithDate = new DateTime(2002, 2, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FullName = "B"
                        },
                        new
                        {
                            StudentId = 3,
                            BrithDate = new DateTime(2002, 3, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FullName = "C"
                        });
                });

            modelBuilder.Entity("WebMVC_DinhTienManh_22103100308.Models.Result", b =>
                {
                    b.HasOne("WebMVC_DinhTienManh_22103100308.Models.Student", "Student")
                        .WithMany("Results")
                        .HasForeignKey("StudentID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Student");
                });

            modelBuilder.Entity("WebMVC_DinhTienManh_22103100308.Models.Student", b =>
                {
                    b.Navigation("Results");
                });
#pragma warning restore 612, 618
        }
    }
}
