// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ngay10_6_Winform.model;

#nullable disable

namespace ngay10_6_Winform.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20250610005758_dintienmanh")]
    partial class dintienmanh
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.36")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("ngay10_6_Winform.model.HoSoKhamBenh", b =>
                {
                    b.Property<int>("MaHoSo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaHoSo"), 1L, 1);

                    b.Property<string>("LoaiBenh")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("MaBenhNhan")
                        .HasColumnType("int");

                    b.Property<DateTime>("NgayKham")
                        .HasColumnType("datetime2");

                    b.Property<bool>("TinhTrangCapCuu")
                        .HasColumnType("bit");

                    b.HasKey("MaHoSo");

                    b.ToTable("HoSoKhamBenhs");

                    b.HasData(
                        new
                        {
                            MaHoSo = 1,
                            LoaiBenh = "sot",
                            MaBenhNhan = 1,
                            NgayKham = new DateTime(2025, 6, 6, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TinhTrangCapCuu = false
                        },
                        new
                        {
                            MaHoSo = 2,
                            LoaiBenh = "sot",
                            MaBenhNhan = 2,
                            NgayKham = new DateTime(2025, 3, 6, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TinhTrangCapCuu = false
                        },
                        new
                        {
                            MaHoSo = 3,
                            LoaiBenh = "sot",
                            MaBenhNhan = 3,
                            NgayKham = new DateTime(2025, 4, 6, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TinhTrangCapCuu = false
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
