// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace WebMVC.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.36")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("WebMVC.Models.ChuyenBay", b =>
                {
                    b.Property<int>("MaChuyenBay")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaChuyenBay"), 1L, 1);

                    b.Property<decimal>("GiaVe")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("MaHanhKhach")
                        .HasColumnType("int");

                    b.Property<DateTime>("NgayBay")
                        .HasColumnType("datetime2");

                    b.Property<string>("NoiDen")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("NoiDi")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("MaChuyenBay");

                    b.HasIndex("MaHanhKhach");

                    b.ToTable("ChuyenBay");

                    b.HasData(
                        new
                        {
                            MaChuyenBay = 1,
                            GiaVe = 1500000m,
                            MaHanhKhach = 1,
                            NgayBay = new DateTime(2025, 6, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            NoiDen = "Ha Noi",
                            NoiDi = "Phu Tho"
                        },
                        new
                        {
                            MaChuyenBay = 2,
                            GiaVe = 15000000m,
                            MaHanhKhach = 1,
                            NgayBay = new DateTime(2025, 6, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            NoiDen = "Quang Ninh",
                            NoiDi = "Ha Noi"
                        },
                        new
                        {
                            MaChuyenBay = 3,
                            GiaVe = 21000000m,
                            MaHanhKhach = 2,
                            NgayBay = new DateTime(2025, 6, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            NoiDen = "Sa Pa",
                            NoiDi = "Ha Noi"
                        });
                });

            modelBuilder.Entity("WebMVC.Models.HanhKhach", b =>
                {
                    b.Property<int>("MaHanhKhach")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaHanhKhach"), 1L, 1);

                    b.Property<string>("HoTen")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("SoCMND")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("SoDT")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("MaHanhKhach");

                    b.ToTable("HanhKhach");

                    b.HasData(
                        new
                        {
                            MaHanhKhach = 1,
                            HoTen = "Nguyen Van A",
                            SoCMND = "123456789",
                            SoDT = "0123456789"
                        },
                        new
                        {
                            MaHanhKhach = 2,
                            HoTen = "Nguyen Van B",
                            SoCMND = "389414794",
                            SoDT = "3741479174"
                        },
                        new
                        {
                            MaHanhKhach = 3,
                            HoTen = "Nguyen Van c",
                            SoCMND = "374914147",
                            SoDT = "3417369746"
                        });
                });

            modelBuilder.Entity("WebMVC.Models.ChuyenBay", b =>
                {
                    b.HasOne("WebMVC.Models.HanhKhach", "HanhKhach")
                        .WithMany("ChuyenBays")
                        .HasForeignKey("MaHanhKhach")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("HanhKhach");
                });

            modelBuilder.Entity("WebMVC.Models.HanhKhach", b =>
                {
                    b.Navigation("ChuyenBays");
                });
#pragma warning restore 612, 618
        }
    }
}
