// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using _30_Itnet_DinhTienManh_22103100308.model;

#nullable disable

namespace _30_Itnet_DinhTienManh_22103100308.Migrations
{
    [DbContext(typeof(AppDBContext))]
    partial class AppDBContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.25")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("_30_Itnet_DinhTienManh_22103100308.model.PhongThucHanh", b =>
                {
                    b.Property<string>("MaPhong")
                        .HasColumnType("nvarchar(450)");

                    b.Property<bool>("CoMayChieu")
                        .HasColumnType("bit");

                    b.Property<DateTime>("NgayDuaVaoSuDung")
                        .HasColumnType("datetime2");

                    b.Property<int>("SucChua")
                        .HasColumnType("int");

                    b.Property<string>("TenPhong")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("MaPhong");

                    b.ToTable("PhongThucHanhs");

                    b.HasData(
                        new
                        {
                            MaPhong = "P01",
                            CoMayChieu = true,
                            NgayDuaVaoSuDung = new DateTime(2022, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            SucChua = 40,
                            TenPhong = "phong A"
                        },
                        new
                        {
                            MaPhong = "P02",
                            CoMayChieu = false,
                            NgayDuaVaoSuDung = new DateTime(2021, 5, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            SucChua = 50,
                            TenPhong = "Phong B"
                        },
                        new
                        {
                            MaPhong = "P003",
                            CoMayChieu = true,
                            NgayDuaVaoSuDung = new DateTime(2020, 9, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            SucChua = 50,
                            TenPhong = "Phòng C"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
